"Changes: Sprites":
- '**/*.rsi/*.png'

"Changes: Map":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/**/*.yml'
    - 'Resources/Prototypes/Maps/**/*.yml'

"Changes: UI":
- '**/*.xaml*'

"Changes: Shaders":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

"No C#":
- all: ["!**/*.cs"]
