- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
<<<<<<< HEAD
  #- Train
=======
  - Train
>>>>>>> fce5269fc0b243b78a8742924f97f31807462877
