- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackSatchelLeather
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
  innerClothingSkirt: ClothingUniformJumpsuitPirate
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateCaptainGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirate
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate
  innerClothingSkirt: ClothingUniformJumpskirtColorLightBrown
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateFirstmateGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirateTricord
    outerClothing: ClothingOuterCoatGentle
  innerClothingSkirt: ClothingUniformJumpsuitPirate
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled
